baseURL = "https://makoto126.github.io/"
languageCode = "zh-cn"
title = "留学生计算机辅导"
theme="archie"
copyright = "© makoto126"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=8 # articles per page

[params]
        mode="auto" # color-mode → light,dark,toggle or auto
        useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
        subtitle = "**WeChat：[makoto126](https://api.qrserver.com/v1/create-qr-code/?size=400x400&data=https%3A%2F%2Fu.wechat.com%2FMIVHFmDiy6cJNd_FQoKcDYE)**"
        mathjax = true # enable MathJax support
        katex = true # enable KaTeX support

# Social Tags

[[params.social]]
name = "WeChat"
icon = "message-circle"
url = "https://api.qrserver.com/v1/create-qr-code/?size=400x400&data=https%3A%2F%2Fu.wechat.com%2FMIVHFmDiy6cJNd_FQoKcDYE"

[[params.social]]
name = "Telegram"
icon = "send"
url = "https://t.me/makoto126"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4